syntax on
set noerrorbells
set hidden
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set relativenumber
set nu
set nohlsearch
set nowrap
set smartcase
set noswapfile
set nobackup
set nowritebackup
set incsearch
set scrolloff=8
set clipboard=unnamed
set cmdheight=2
set cursorline
set shortmess+=c
set backspace=indent,eol,start
set cursorline
hi CursorLine term=bold cterm=bold guibg=Grey40
